name: khatabook
description: KhataBook - business accounting, khata, car daily rent and driver earnings.
publish_to: "none"
version: 2.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
    - assets/khatabook_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/khatabook_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/khatabook_logo.png
